# Commands to start on workspace startup
tasks:
  - init: cd front && npm install
    command: cd front && npm run serve
# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview
  - port: 8069
    visibility: public
    onOpen: open-preview